name: create-management-group

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  create-management-group:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy Management Group
      uses: azure/arm-deploy@v1
        with:
          # Path to your Bicep file for management group
          template: '.deploy/main.bicep'
        .
