name: create-management-group

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  create-management-group:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Azure (Optional)
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Assuming service principal authentication
        auth-type: SERVICE_PRINCIPAL
    - name: Deploy Management Group
      uses: azure/arm-deploy@v1
      with:
          # Path to your Bicep file for management group
          template: './create-management-group.bicep'
          # Optional parameters for the Bicep file (if needed)
          # parameters: ...
